name: Build/release

on:
    push:
      # Sequence of patterns matched against refs/tags
      tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  release:
    runs-on: ${{ matrix.os }}

    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Checkout code
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: Build project
        uses: actions/setup-node@v4
        with:
          node-version: '16'
          cache: 'yarn' 
      - run: yarn install
      - run: yarn global add electron-builder
      - run: yarn run buildwin64

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.0
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload asset
        uses: actions/upload-release-asset@v1.0.1
        env:
            RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        with: 
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: ./dist/control-production-slave*.exe
            asset_name: control-production-slave*.exe
            asset_content_type: application/exe
